"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.subtitle": "Here's what's happening with your competitors today.",
    "dashboard.competitors_tracked": "Competitors Tracked",
    "dashboard.active_tracking": "Active tracking",
    "dashboard.total_features": "Total Features Tracked",
    "dashboard.across_all": "Across all competitors",
    "dashboard.market_mood": "Market Mood",
    "dashboard.avg_growth": "Avg growth",
    "dashboard.news_items": "News Items",
    "dashboard.recent_updates": "Recent updates",
    "dashboard.weekly_activity": "Weekly Activity Overview",
    "dashboard.weekly_activity_desc": "Activity trends across your competitors this week",
    "dashboard.competitor_activity": "Competitor Activity",
    "dashboard.competitor_activity_desc": "Real-time updates on your tracked competitors",
    "dashboard.no_competitors": "No competitors selected yet.",
    "dashboard.add_competitors": "Add Competitors",
    "dashboard.features": "features",
    "dashboard.market_share": "market share",
    "dashboard.news_digest": "News Digest",
    "dashboard.news_digest_desc": "Latest product launches and updates",
    "dashboard.all_news": "All News",
    "dashboard.key_insights": "Key Insights",
    "dashboard.you_are_first": "You are first",
    "dashboard.first_to_market": "Be the first to market with innovative features.",
    "dashboard.view_opportunities": "View opportunities →",
    "dashboard.competitor_planning": "Competitor planning this",
    "dashboard.stay_informed": "Stay informed about upcoming competitor releases.",
    "dashboard.see_predictions": "See predictions →",
    "dashboard.competitor_lacks": "Competitor lacks this",
    "dashboard.identify_gaps": "Identify gaps in competitor offerings and capitalize.",
    "dashboard.explore_gaps": "Explore gaps →",
    "dashboard.see_compare": "See how you compare",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.export_report": "Export Report",
    "dashboard.get_notified": "Get Notified",
    "dashboard.compare_features": "Compare Features",
    "dashboard.upcoming_events": "Upcoming Events",
    "dashboard.today": "Today",
    "dashboard.this_week": "This Week",
    "dashboard.this_month": "This Month",
    "dashboard.bullish": "Bullish",
    "dashboard.neutral": "Neutral",
    "dashboard.bearish": "Bearish",
    "dashboard.high": "high",
    "dashboard.medium": "medium",
    "dashboard.low": "low",
    "dashboard.view_full_comparison": "View Full Comparison",
    "dashboard.set_alert": "Set Alert",
    "dashboard.market_share_label": "Market Share",
    "dashboard.growth_rate": "Growth Rate",
    "dashboard.features_tracked": "Features Tracked",

    // Navbar
    "nav.dashboard": "Dashboard",
    "nav.competitors": "Competitors",
    "nav.insights": "Insights",
    "nav.news_digest": "News Digest",
    "nav.reports": "Reports",
    "nav.alerts": "Alerts",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.logout": "Logout",

    // Settings
    "settings.title": "Settings",
    "settings.appearance": "Appearance",
    "settings.appearance_desc": "Customize how the app looks on your device",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.language_region": "Language & Region",
    "settings.language_region_desc": "Select your preferred language and regional settings",
    "settings.display_language": "Display Language",
    "settings.choose_language": "Choose your preferred language",
    "settings.competitors": "Competitors",
    "settings.competitors_desc": "Manage your tracked competitors",
    "settings.competitor_list": "Competitor List",
    "settings.manage_competitors": "Manage your list of followed competitors.",
    "settings.manage": "Manage",
    "settings.notifications": "Notifications",
    "settings.notifications_desc": "Configure how you receive alerts and updates",
    "settings.slack": "Slack",
    "settings.slack_desc": "Get notified in your workspace when competitors make changes.",
    "settings.email": "Email",
    "settings.email_desc": "Receive email digests about competitor activities.",
    "settings.data_privacy": "Data & Privacy",
    "settings.data_privacy_desc": "Control your data and privacy preferences",
    "settings.auto_refresh": "Auto-refresh Data",
    "settings.auto_refresh_desc": "Automatically update competitor data in real-time",
    "settings.usage_analytics": "Usage Analytics",
    "settings.usage_analytics_desc": "Help improve the product by sharing anonymous usage data",
    "settings.download_data": "Download My Data",

    // Common
    "common.home": "Home",
    "common.invite_team": "Invite team",
    "common.help_docs": "Help and docs",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",

    // Days
    "days.mon": "Mon",
    "days.tue": "Tue",
    "days.wed": "Wed",
    "days.thu": "Thu",
    "days.fri": "Fri",
    "days.sat": "Sat",
    "days.sun": "Sun",
  },
  hi: {
    // Dashboard
    "dashboard.welcome": "वापसी पर स्वागत है",
    "dashboard.subtitle": "आज आपके प्रतिस्पर्धियों के साथ क्या हो रहा है।",
    "dashboard.competitors_tracked": "ट्रैक किए गए प्रतिस्पर्धी",
    "dashboard.active_tracking": "सक्रिय ट्रैकिंग",
    "dashboard.total_features": "कुल सुविधाएं ट्रैक की गईं",
    "dashboard.across_all": "सभी प्रतिस्पर्धियों में",
    "dashboard.market_mood": "बाजार का मूड",
    "dashboard.avg_growth": "औसत वृद्धि",
    "dashboard.news_items": "समाचार आइटम",
    "dashboard.recent_updates": "हाल के अपडेट",
    "dashboard.weekly_activity": "साप्ताहिक गतिविधि अवलोकन",
    "dashboard.weekly_activity_desc": "इस सप्ताह आपके प्रतिस्पर्धियों में गतिविधि के रुझान",
    "dashboard.competitor_activity": "प्रतिस्पर्धी गतिविधि",
    "dashboard.competitor_activity_desc": "आपके ट्रैक किए गए प्रतिस्पर्धियों पर रीयल-टाइम अपडेट",
    "dashboard.no_competitors": "अभी तक कोई प्रतिस्पर्धी नहीं चुना गया।",
    "dashboard.add_competitors": "प्रतिस्पर्धी जोड़ें",
    "dashboard.features": "सुविधाएं",
    "dashboard.market_share": "बाजार हिस्सेदारी",
    "dashboard.news_digest": "समाचार सारांश",
    "dashboard.news_digest_desc": "नवीनतम उत्पाद लॉन्च और अपडेट",
    "dashboard.all_news": "सभी समाचार",
    "dashboard.key_insights": "मुख्य अंतर्दृष्टि",
    "dashboard.you_are_first": "आप पहले हैं",
    "dashboard.first_to_market": "नवीन सुविधाओं के साथ बाजार में पहले बनें।",
    "dashboard.view_opportunities": "अवसर देखें →",
    "dashboard.competitor_planning": "प्रतिस्पर्धी इसकी योजना बना रहा है",
    "dashboard.stay_informed": "आगामी प्रतिस्पर्धी रिलीज के बारे में सूचित रहें।",
    "dashboard.see_predictions": "भविष्यवाणियां देखें →",
    "dashboard.competitor_lacks": "प्रतिस्पर्धी में यह कमी है",
    "dashboard.identify_gaps": "प्रतिस्पर्धी पेशकशों में अंतराल की पहचान करें और लाभ उठाएं।",
    "dashboard.explore_gaps": "अंतराल का अन्वेषण करें →",
    "dashboard.see_compare": "देखें कि आप कैसे तुलना करते हैं",
    "dashboard.quick_actions": "त्वरित क्रियाएं",
    "dashboard.export_report": "रिपोर्ट निर्यात करें",
    "dashboard.get_notified": "सूचित हों",
    "dashboard.compare_features": "सुविधाओं की तुलना करें",
    "dashboard.upcoming_events": "आगामी कार्यक्रम",
    "dashboard.today": "आज",
    "dashboard.this_week": "इस सप्ताह",
    "dashboard.this_month": "इस महीने",
    "dashboard.bullish": "तेजी",
    "dashboard.neutral": "तटस्थ",
    "dashboard.bearish": "मंदी",
    "dashboard.high": "उच्च",
    "dashboard.medium": "मध्यम",
    "dashboard.low": "निम्न",
    "dashboard.view_full_comparison": "पूर्ण तुलना देखें",
    "dashboard.set_alert": "अलर्ट सेट करें",
    "dashboard.market_share_label": "बाजार हिस्सेदारी",
    "dashboard.growth_rate": "वृद्धि दर",
    "dashboard.features_tracked": "ट्रैक की गई सुविधाएं",

    // Navbar
    "nav.dashboard": "डैशबोर्ड",
    "nav.competitors": "प्रतिस्पर्धी",
    "nav.insights": "अंतर्दृष्टि",
    "nav.news_digest": "समाचार सारांश",
    "nav.reports": "रिपोर्ट",
    "nav.alerts": "अलर्ट",
    "nav.settings": "सेटिंग्स",
    "nav.profile": "प्रोफ़ाइल",
    "nav.logout": "लॉगआउट",

    // Settings
    "settings.title": "सेटिंग्स",
    "settings.appearance": "दिखावट",
    "settings.appearance_desc": "अपने डिवाइस पर ऐप कैसा दिखता है, इसे अनुकूलित करें",
    "settings.theme": "थीम",
    "settings.light": "हल्का",
    "settings.dark": "गहरा",
    "settings.system": "सिस्टम",
    "settings.language_region": "भाषा और क्षेत्र",
    "settings.language_region_desc": "अपनी पसंदीदा भाषा और क्षेत्रीय सेटिंग्स चुनें",
    "settings.display_language": "प्रदर्शन भाषा",
    "settings.choose_language": "अपनी पसंदीदा भाषा चुनें",
    "settings.competitors": "प्रतिस्पर्धी",
    "settings.competitors_desc": "अपने ट्रैक किए गए प्रतिस्पर्धियों को प्रबंधित करें",
    "settings.competitor_list": "प्रतिस्पर्धी सूची",
    "settings.manage_competitors": "अपने फॉलो किए गए प्रतिस्पर्धियों की सूची प्रबंधित करें।",
    "settings.manage": "प्रबंधित करें",
    "settings.notifications": "सूचनाएं",
    "settings.notifications_desc": "कॉन्फ़िगर करें कि आप अलर्ट और अपडेट कैसे प्राप्त करते हैं",
    "settings.slack": "स्लैक",
    "settings.slack_desc": "जब प्रतिस्पर्धी परिवर्तन करते हैं तो अपने कार्यक्षेत्र में सूचित हों।",
    "settings.email": "ईमेल",
    "settings.email_desc": "प्रतिस्पर्धी गतिविधियों के बारे में ईमेल सारांश प्राप्त करें।",
    "settings.data_privacy": "डेटा और गोपनीयता",
    "settings.data_privacy_desc": "अपने डेटा और गोपनीयता प्राथमिकताओं को नियंत्रित करें",
    "settings.auto_refresh": "ऑटो-रिफ्रेश डेटा",
    "settings.auto_refresh_desc": "रीयल-टाइम में प्रतिस्पर्धी डेटा को स्वचालित रूप से अपडेट करें",
    "settings.usage_analytics": "उपयोग विश्लेषण",
    "settings.usage_analytics_desc": "गुमनाम उपयोग डेटा साझा करके उत्पाद को बेहतर बनाने में मदद करें",
    "settings.download_data": "मेरा डेटा डाउनलोड करें",

    // Common
    "common.home": "होम",
    "common.invite_team": "टीम को आमंत्रित करें",
    "common.help_docs": "सहायता और दस्तावेज़",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.close": "बंद करें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफलता",

    // Days
    "days.mon": "सोम",
    "days.tue": "मंगल",
    "days.wed": "बुध",
    "days.thu": "गुरु",
    "days.fri": "शुक्र",
    "days.sat": "शनि",
    "days.sun": "रवि",
  },
  es: {
    // Dashboard
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.subtitle": "Esto es lo que está pasando con tus competidores hoy.",
    "dashboard.competitors_tracked": "Competidores Rastreados",
    "dashboard.active_tracking": "Seguimiento activo",
    "dashboard.total_features": "Total de Características Rastreadas",
    "dashboard.across_all": "En todos los competidores",
    "dashboard.market_mood": "Estado del Mercado",
    "dashboard.avg_growth": "Crecimiento promedio",
    "dashboard.news_items": "Noticias",
    "dashboard.recent_updates": "Actualizaciones recientes",
    "dashboard.weekly_activity": "Resumen de Actividad Semanal",
    "dashboard.weekly_activity_desc": "Tendencias de actividad de tus competidores esta semana",
    "dashboard.competitor_activity": "Actividad de Competidores",
    "dashboard.competitor_activity_desc": "Actualizaciones en tiempo real de tus competidores rastreados",
    "dashboard.no_competitors": "Aún no se han seleccionado competidores.",
    "dashboard.add_competitors": "Agregar Competidores",
    "dashboard.features": "características",
    "dashboard.market_share": "cuota de mercado",
    "dashboard.news_digest": "Resumen de Noticias",
    "dashboard.news_digest_desc": "Últimos lanzamientos de productos y actualizaciones",
    "dashboard.all_news": "Todas las Noticias",
    "dashboard.key_insights": "Perspectivas Clave",
    "dashboard.you_are_first": "Eres el primero",
    "dashboard.first_to_market": "Sé el primero en el mercado con características innovadoras.",
    "dashboard.view_opportunities": "Ver oportunidades →",
    "dashboard.competitor_planning": "Competidor planea esto",
    "dashboard.stay_informed": "Mantente informado sobre próximos lanzamientos de competidores.",
    "dashboard.see_predictions": "Ver predicciones →",
    "dashboard.competitor_lacks": "Al competidor le falta esto",
    "dashboard.identify_gaps": "Identifica brechas en las ofertas de competidores y capitaliza.",
    "dashboard.explore_gaps": "Explorar brechas →",
    "dashboard.see_compare": "Ver cómo te comparas",
    "dashboard.quick_actions": "Acciones Rápidas",
    "dashboard.export_report": "Exportar Informe",
    "dashboard.get_notified": "Recibir Notificaciones",
    "dashboard.compare_features": "Comparar Características",
    "dashboard.upcoming_events": "Próximos Eventos",
    "dashboard.today": "Hoy",
    "dashboard.this_week": "Esta Semana",
    "dashboard.this_month": "Este Mes",
    "dashboard.bullish": "Alcista",
    "dashboard.neutral": "Neutral",
    "dashboard.bearish": "Bajista",
    "dashboard.high": "alto",
    "dashboard.medium": "medio",
    "dashboard.low": "bajo",
    "dashboard.view_full_comparison": "Ver Comparación Completa",
    "dashboard.set_alert": "Configurar Alerta",
    "dashboard.market_share_label": "Cuota de Mercado",
    "dashboard.growth_rate": "Tasa de Crecimiento",
    "dashboard.features_tracked": "Características Rastreadas",

    // Navbar
    "nav.dashboard": "Panel",
    "nav.competitors": "Competidores",
    "nav.insights": "Perspectivas",
    "nav.news_digest": "Resumen de Noticias",
    "nav.reports": "Informes",
    "nav.alerts": "Alertas",
    "nav.settings": "Configuración",
    "nav.profile": "Perfil",
    "nav.logout": "Cerrar Sesión",

    // Settings
    "settings.title": "Configuración",
    "settings.appearance": "Apariencia",
    "settings.appearance_desc": "Personaliza cómo se ve la aplicación en tu dispositivo",
    "settings.theme": "Tema",
    "settings.light": "Claro",
    "settings.dark": "Oscuro",
    "settings.system": "Sistema",
    "settings.language_region": "Idioma y Región",
    "settings.language_region_desc": "Selecciona tu idioma y configuración regional preferidos",
    "settings.display_language": "Idioma de Visualización",
    "settings.choose_language": "Elige tu idioma preferido",
    "settings.competitors": "Competidores",
    "settings.competitors_desc": "Administra tus competidores rastreados",
    "settings.competitor_list": "Lista de Competidores",
    "settings.manage_competitors": "Administra tu lista de competidores seguidos.",
    "settings.manage": "Administrar",
    "settings.notifications": "Notificaciones",
    "settings.notifications_desc": "Configura cómo recibes alertas y actualizaciones",
    "settings.slack": "Slack",
    "settings.slack_desc": "Recibe notificaciones en tu espacio de trabajo cuando los competidores hagan cambios.",
    "settings.email": "Correo Electrónico",
    "settings.email_desc": "Recibe resúmenes por correo electrónico sobre actividades de competidores.",
    "settings.data_privacy": "Datos y Privacidad",
    "settings.data_privacy_desc": "Controla tus preferencias de datos y privacidad",
    "settings.auto_refresh": "Actualización Automática de Datos",
    "settings.auto_refresh_desc": "Actualiza automáticamente los datos de competidores en tiempo real",
    "settings.usage_analytics": "Análisis de Uso",
    "settings.usage_analytics_desc": "Ayuda a mejorar el producto compartiendo datos de uso anónimos",
    "settings.download_data": "Descargar Mis Datos",

    // Common
    "common.home": "Inicio",
    "common.invite_team": "Invitar equipo",
    "common.help_docs": "Ayuda y documentos",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.close": "Cerrar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",

    // Days
    "days.mon": "Lun",
    "days.tue": "Mar",
    "days.wed": "Mié",
    "days.thu": "Jue",
    "days.fri": "Vie",
    "days.sat": "Sáb",
    "days.sun": "Dom",
  },
  fr: {
    // Dashboard
    "dashboard.welcome": "Bon retour",
    "dashboard.subtitle": "Voici ce qui se passe avec vos concurrents aujourd'hui.",
    "dashboard.competitors_tracked": "Concurrents Suivis",
    "dashboard.active_tracking": "Suivi actif",
    "dashboard.total_features": "Total des Fonctionnalités Suivies",
    "dashboard.across_all": "Sur tous les concurrents",
    "dashboard.market_mood": "Humeur du Marché",
    "dashboard.avg_growth": "Croissance moyenne",
    "dashboard.news_items": "Actualités",
    "dashboard.recent_updates": "Mises à jour récentes",
    "dashboard.weekly_activity": "Aperçu de l'Activité Hebdomadaire",
    "dashboard.weekly_activity_desc": "Tendances d'activité de vos concurrents cette semaine",
    "dashboard.competitor_activity": "Activité des Concurrents",
    "dashboard.competitor_activity_desc": "Mises à jour en temps réel sur vos concurrents suivis",
    "dashboard.no_competitors": "Aucun concurrent sélectionné pour le moment.",
    "dashboard.add_competitors": "Ajouter des Concurrents",
    "dashboard.features": "fonctionnalités",
    "dashboard.market_share": "part de marché",
    "dashboard.news_digest": "Résumé des Actualités",
    "dashboard.news_digest_desc": "Derniers lancements de produits et mises à jour",
    "dashboard.all_news": "Toutes les Actualités",
    "dashboard.key_insights": "Informations Clés",
    "dashboard.you_are_first": "Vous êtes le premier",
    "dashboard.first_to_market": "Soyez le premier sur le marché avec des fonctionnalités innovantes.",
    "dashboard.view_opportunities": "Voir les opportunités →",
    "dashboard.competitor_planning": "Le concurrent planifie cela",
    "dashboard.stay_informed": "Restez informé des prochaines versions des concurrents.",
    "dashboard.see_predictions": "Voir les prédictions →",
    "dashboard.competitor_lacks": "Le concurrent manque de cela",
    "dashboard.identify_gaps": "Identifiez les lacunes dans les offres des concurrents et capitalisez.",
    "dashboard.explore_gaps": "Explorer les lacunes →",
    "dashboard.see_compare": "Voir comment vous vous comparez",
    "dashboard.quick_actions": "Actions Rapides",
    "dashboard.export_report": "Exporter le Rapport",
    "dashboard.get_notified": "Être Notifié",
    "dashboard.compare_features": "Comparer les Fonctionnalités",
    "dashboard.upcoming_events": "Événements à Venir",
    "dashboard.today": "Aujourd'hui",
    "dashboard.this_week": "Cette Semaine",
    "dashboard.this_month": "Ce Mois",
    "dashboard.bullish": "Haussier",
    "dashboard.neutral": "Neutre",
    "dashboard.bearish": "Baissier",
    "dashboard.high": "élevé",
    "dashboard.medium": "moyen",
    "dashboard.low": "faible",
    "dashboard.view_full_comparison": "Voir la Comparaison Complète",
    "dashboard.set_alert": "Définir une Alerte",
    "dashboard.market_share_label": "Part de Marché",
    "dashboard.growth_rate": "Taux de Croissance",
    "dashboard.features_tracked": "Fonctionnalités Suivies",

    // Navbar
    "nav.dashboard": "Tableau de Bord",
    "nav.competitors": "Concurrents",
    "nav.insights": "Informations",
    "nav.news_digest": "Résumé des Actualités",
    "nav.reports": "Rapports",
    "nav.alerts": "Alertes",
    "nav.settings": "Paramètres",
    "nav.profile": "Profil",
    "nav.logout": "Déconnexion",

    // Settings
    "settings.title": "Paramètres",
    "settings.appearance": "Apparence",
    "settings.appearance_desc": "Personnalisez l'apparence de l'application sur votre appareil",
    "settings.theme": "Thème",
    "settings.light": "Clair",
    "settings.dark": "Sombre",
    "settings.system": "Système",
    "settings.language_region": "Langue et Région",
    "settings.language_region_desc": "Sélectionnez votre langue et vos paramètres régionaux préférés",
    "settings.display_language": "Langue d'Affichage",
    "settings.choose_language": "Choisissez votre langue préférée",
    "settings.competitors": "Concurrents",
    "settings.competitors_desc": "Gérez vos concurrents suivis",
    "settings.competitor_list": "Liste des Concurrents",
    "settings.manage_competitors": "Gérez votre liste de concurrents suivis.",
    "settings.manage": "Gérer",
    "settings.notifications": "Notifications",
    "settings.notifications_desc": "Configurez comment vous recevez les alertes et les mises à jour",
    "settings.slack": "Slack",
    "settings.slack_desc":
      "Soyez notifié dans votre espace de travail lorsque les concurrents apportent des modifications.",
    "settings.email": "E-mail",
    "settings.email_desc": "Recevez des résumés par e-mail sur les activités des concurrents.",
    "settings.data_privacy": "Données et Confidentialité",
    "settings.data_privacy_desc": "Contrôlez vos préférences de données et de confidentialité",
    "settings.auto_refresh": "Actualisation Automatique des Données",
    "settings.auto_refresh_desc": "Mettez à jour automatiquement les données des concurrents en temps réel",
    "settings.usage_analytics": "Analyse d'Utilisation",
    "settings.usage_analytics_desc": "Aidez à améliorer le produit en partageant des données d'utilisation anonymes",
    "settings.download_data": "Télécharger Mes Données",

    // Common
    "common.home": "Accueil",
    "common.invite_team": "Inviter l'équipe",
    "common.help_docs": "Aide et documents",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.close": "Fermer",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",

    // Days
    "days.mon": "Lun",
    "days.tue": "Mar",
    "days.wed": "Mer",
    "days.thu": "Jeu",
    "days.fri": "Ven",
    "days.sat": "Sam",
    "days.sun": "Dim",
  },
  de: {
    // Dashboard
    "dashboard.welcome": "Willkommen zurück",
    "dashboard.subtitle": "Hier ist, was heute mit Ihren Wettbewerbern passiert.",
    "dashboard.competitors_tracked": "Verfolgte Wettbewerber",
    "dashboard.active_tracking": "Aktive Verfolgung",
    "dashboard.total_features": "Gesamt Verfolgte Funktionen",
    "dashboard.across_all": "Über alle Wettbewerber",
    "dashboard.market_mood": "Marktstimmung",
    "dashboard.avg_growth": "Durchschn. Wachstum",
    "dashboard.news_items": "Nachrichten",
    "dashboard.recent_updates": "Aktuelle Updates",
    "dashboard.weekly_activity": "Wöchentliche Aktivitätsübersicht",
    "dashboard.weekly_activity_desc": "Aktivitätstrends Ihrer Wettbewerber diese Woche",
    "dashboard.competitor_activity": "Wettbewerberaktivität",
    "dashboard.competitor_activity_desc": "Echtzeit-Updates zu Ihren verfolgten Wettbewerbern",
    "dashboard.no_competitors": "Noch keine Wettbewerber ausgewählt.",
    "dashboard.add_competitors": "Wettbewerber Hinzufügen",
    "dashboard.features": "Funktionen",
    "dashboard.market_share": "Marktanteil",
    "dashboard.news_digest": "Nachrichtenübersicht",
    "dashboard.news_digest_desc": "Neueste Produkteinführungen und Updates",
    "dashboard.all_news": "Alle Nachrichten",
    "dashboard.key_insights": "Wichtige Erkenntnisse",
    "dashboard.you_are_first": "Sie sind der Erste",
    "dashboard.first_to_market": "Seien Sie der Erste auf dem Markt mit innovativen Funktionen.",
    "dashboard.view_opportunities": "Chancen ansehen →",
    "dashboard.competitor_planning": "Wettbewerber plant dies",
    "dashboard.stay_informed": "Bleiben Sie über bevorstehende Wettbewerber-Releases informiert.",
    "dashboard.see_predictions": "Vorhersagen ansehen →",
    "dashboard.competitor_lacks": "Wettbewerber fehlt dies",
    "dashboard.identify_gaps": "Identifizieren Sie Lücken in Wettbewerberangeboten und nutzen Sie sie.",
    "dashboard.explore_gaps": "Lücken erkunden →",
    "dashboard.see_compare": "Sehen Sie, wie Sie sich vergleichen",
    "dashboard.quick_actions": "Schnellaktionen",
    "dashboard.export_report": "Bericht Exportieren",
    "dashboard.get_notified": "Benachrichtigt Werden",
    "dashboard.compare_features": "Funktionen Vergleichen",
    "dashboard.upcoming_events": "Bevorstehende Ereignisse",
    "dashboard.today": "Heute",
    "dashboard.this_week": "Diese Woche",
    "dashboard.this_month": "Diesen Monat",
    "dashboard.bullish": "Bullisch",
    "dashboard.neutral": "Neutral",
    "dashboard.bearish": "Bärisch",
    "dashboard.high": "hoch",
    "dashboard.medium": "mittel",
    "dashboard.low": "niedrig",
    "dashboard.view_full_comparison": "Vollständigen Vergleich Anzeigen",
    "dashboard.set_alert": "Alarm Einstellen",
    "dashboard.market_share_label": "Marktanteil",
    "dashboard.growth_rate": "Wachstumsrate",
    "dashboard.features_tracked": "Verfolgte Funktionen",

    // Navbar
    "nav.dashboard": "Dashboard",
    "nav.competitors": "Wettbewerber",
    "nav.insights": "Erkenntnisse",
    "nav.news_digest": "Nachrichtenübersicht",
    "nav.reports": "Berichte",
    "nav.alerts": "Alarme",
    "nav.settings": "Einstellungen",
    "nav.profile": "Profil",
    "nav.logout": "Abmelden",

    // Settings
    "settings.title": "Einstellungen",
    "settings.appearance": "Erscheinungsbild",
    "settings.appearance_desc": "Passen Sie an, wie die App auf Ihrem Gerät aussieht",
    "settings.theme": "Thema",
    "settings.light": "Hell",
    "settings.dark": "Dunkel",
    "settings.system": "System",
    "settings.language_region": "Sprache & Region",
    "settings.language_region_desc": "Wählen Sie Ihre bevorzugte Sprache und regionale Einstellungen",
    "settings.display_language": "Anzeigesprache",
    "settings.choose_language": "Wählen Sie Ihre bevorzugte Sprache",
    "settings.competitors": "Wettbewerber",
    "settings.competitors_desc": "Verwalten Sie Ihre verfolgten Wettbewerber",
    "settings.competitor_list": "Wettbewerberliste",
    "settings.manage_competitors": "Verwalten Sie Ihre Liste der verfolgten Wettbewerber.",
    "settings.manage": "Verwalten",
    "settings.notifications": "Benachrichtigungen",
    "settings.notifications_desc": "Konfigurieren Sie, wie Sie Alarme und Updates erhalten",
    "settings.slack": "Slack",
    "settings.slack_desc": "Werden Sie in Ihrem Arbeitsbereich benachrichtigt, wenn Wettbewerber Änderungen vornehmen.",
    "settings.email": "E-Mail",
    "settings.email_desc": "Erhalten Sie E-Mail-Zusammenfassungen über Wettbewerberaktivitäten.",
    "settings.data_privacy": "Daten & Datenschutz",
    "settings.data_privacy_desc": "Kontrollieren Sie Ihre Daten- und Datenschutzeinstellungen",
    "settings.auto_refresh": "Automatische Datenaktualisierung",
    "settings.auto_refresh_desc": "Aktualisieren Sie Wettbewerberdaten automatisch in Echtzeit",
    "settings.usage_analytics": "Nutzungsanalyse",
    "settings.usage_analytics_desc": "Helfen Sie, das Produkt zu verbessern, indem Sie anonyme Nutzungsdaten teilen",
    "settings.download_data": "Meine Daten Herunterladen",

    // Common
    "common.home": "Startseite",
    "common.invite_team": "Team einladen",
    "common.help_docs": "Hilfe und Dokumente",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.close": "Schließen",
    "common.loading": "Wird geladen...",
    "common.error": "Fehler",
    "common.success": "Erfolg",

    // Days
    "days.mon": "Mo",
    "days.tue": "Di",
    "days.wed": "Mi",
    "days.thu": "Do",
    "days.fri": "Fr",
    "days.sat": "Sa",
    "days.sun": "So",
  },
  zh: {
    // Dashboard
    "dashboard.welcome": "欢迎回来",
    "dashboard.subtitle": "这是您的竞争对手今天的情况。",
    "dashboard.competitors_tracked": "跟踪的竞争对手",
    "dashboard.active_tracking": "主动跟踪",
    "dashboard.total_features": "跟踪的总功能",
    "dashboard.across_all": "所有竞争对手",
    "dashboard.market_mood": "市场情绪",
    "dashboard.avg_growth": "平均增长",
    "dashboard.news_items": "新闻项目",
    "dashboard.recent_updates": "最近更新",
    "dashboard.weekly_activity": "每周活动概览",
    "dashboard.weekly_activity_desc": "本周您的竞争对手的活动趋势",
    "dashboard.competitor_activity": "竞争对手活动",
    "dashboard.competitor_activity_desc": "您跟踪的竞争对手的实时更新",
    "dashboard.no_competitors": "尚未选择竞争对手。",
    "dashboard.add_competitors": "添加竞争对手",
    "dashboard.features": "功能",
    "dashboard.market_share": "市场份额",
    "dashboard.news_digest": "新闻摘要",
    "dashboard.news_digest_desc": "最新产品发布和更新",
    "dashboard.all_news": "所有新闻",
    "dashboard.key_insights": "关键见解",
    "dashboard.you_are_first": "您是第一个",
    "dashboard.first_to_market": "以创新功能率先进入市场。",
    "dashboard.view_opportunities": "查看机会 →",
    "dashboard.competitor_planning": "竞争对手正在计划这个",
    "dashboard.stay_informed": "了解即将发布的竞争对手版本。",
    "dashboard.see_predictions": "查看预测 →",
    "dashboard.competitor_lacks": "竞争对手缺少这个",
    "dashboard.identify_gaps": "识别竞争对手产品中的差距并加以利用。",
    "dashboard.explore_gaps": "探索差距 →",
    "dashboard.see_compare": "看看您的比较",
    "dashboard.quick_actions": "快速操作",
    "dashboard.export_report": "导出报告",
    "dashboard.get_notified": "获取通知",
    "dashboard.compare_features": "比较功能",
    "dashboard.upcoming_events": "即将举行的活动",
    "dashboard.today": "今天",
    "dashboard.this_week": "本周",
    "dashboard.this_month": "本月",
    "dashboard.bullish": "看涨",
    "dashboard.neutral": "中性",
    "dashboard.bearish": "看跌",
    "dashboard.high": "高",
    "dashboard.medium": "中",
    "dashboard.low": "低",
    "dashboard.view_full_comparison": "查看完整比较",
    "dashboard.set_alert": "设置警报",
    "dashboard.market_share_label": "市场份额",
    "dashboard.growth_rate": "增长率",
    "dashboard.features_tracked": "跟踪的功能",

    // Navbar
    "nav.dashboard": "仪表板",
    "nav.competitors": "竞争对手",
    "nav.insights": "见解",
    "nav.news_digest": "新闻摘要",
    "nav.reports": "报告",
    "nav.alerts": "警报",
    "nav.settings": "设置",
    "nav.profile": "个人资料",
    "nav.logout": "登出",

    // Settings
    "settings.title": "设置",
    "settings.appearance": "外观",
    "settings.appearance_desc": "自定义应用在您设备上的外观",
    "settings.theme": "主题",
    "settings.light": "浅色",
    "settings.dark": "深色",
    "settings.system": "系统",
    "settings.language_region": "语言和地区",
    "settings.language_region_desc": "选择您的首选语言和地区设置",
    "settings.display_language": "显示语言",
    "settings.choose_language": "选择您的首选语言",
    "settings.competitors": "竞争对手",
    "settings.competitors_desc": "管理您跟踪的竞争对手",
    "settings.competitor_list": "竞争对手列表",
    "settings.manage_competitors": "管理您关注的竞争对手列表。",
    "settings.manage": "管理",
    "settings.notifications": "通知",
    "settings.notifications_desc": "配置您如何接收警报和更新",
    "settings.slack": "Slack",
    "settings.slack_desc": "当竞争对手进行更改时，在您的工作区中收到通知。",
    "settings.email": "电子邮件",
    "settings.email_desc": "接收有关竞争对手活动的电子邮件摘要。",
    "settings.data_privacy": "数据和隐私",
    "settings.data_privacy_desc": "控制您的数据和隐私偏好",
    "settings.auto_refresh": "自动刷新数据",
    "settings.auto_refresh_desc": "实时自动更新竞争对手数据",
    "settings.usage_analytics": "使用分析",
    "settings.usage_analytics_desc": "通过共享匿名使用数据帮助改进产品",
    "settings.download_data": "下载我的数据",

    // Common
    "common.home": "主页",
    "common.invite_team": "邀请团队",
    "common.help_docs": "帮助和文档",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.close": "关闭",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",

    // Days
    "days.mon": "周一",
    "days.tue": "周二",
    "days.wed": "周三",
    "days.thu": "周四",
    "days.fri": "周五",
    "days.sat": "周六",
    "days.sun": "周日",
  },
  ja: {
    // Dashboard
    "dashboard.welcome": "おかえりなさい",
    "dashboard.subtitle": "今日の競合他社の動向です。",
    "dashboard.competitors_tracked": "追跡中の競合他社",
    "dashboard.active_tracking": "アクティブな追跡",
    "dashboard.total_features": "追跡中の総機能数",
    "dashboard.across_all": "すべての競合他社",
    "dashboard.market_mood": "市場の雰囲気",
    "dashboard.avg_growth": "平均成長率",
    "dashboard.news_items": "ニュース項目",
    "dashboard.recent_updates": "最近の更新",
    "dashboard.weekly_activity": "週間アクティビティ概要",
    "dashboard.weekly_activity_desc": "今週の競合他社のアクティビティトレンド",
    "dashboard.competitor_activity": "競合他社のアクティビティ",
    "dashboard.competitor_activity_desc": "追跡中の競合他社のリアルタイム更新",
    "dashboard.no_competitors": "まだ競合他社が選択されていません。",
    "dashboard.add_competitors": "競合他社を追加",
    "dashboard.features": "機能",
    "dashboard.market_share": "市場シェア",
    "dashboard.news_digest": "ニュースダイジェスト",
    "dashboard.news_digest_desc": "最新の製品発表と更新",
    "dashboard.all_news": "すべてのニュース",
    "dashboard.key_insights": "主要な洞察",
    "dashboard.you_are_first": "あなたが最初です",
    "dashboard.first_to_market": "革新的な機能で市場に最初に参入しましょう。",
    "dashboard.view_opportunities": "機会を見る →",
    "dashboard.competitor_planning": "競合他社がこれを計画中",
    "dashboard.stay_informed": "今後の競合他社のリリースについて情報を入手しましょう。",
    "dashboard.see_predictions": "予測を見る →",
    "dashboard.competitor_lacks": "競合他社にはこれがありません",
    "dashboard.identify_gaps": "競合他社の提供物のギャップを特定し、活用しましょう。",
    "dashboard.explore_gaps": "ギャップを探る →",
    "dashboard.see_compare": "比較を見る",
    "dashboard.quick_actions": "クイックアクション",
    "dashboard.export_report": "レポートをエクスポート",
    "dashboard.get_notified": "通知を受け取る",
    "dashboard.compare_features": "機能を比較",
    "dashboard.upcoming_events": "今後のイベント",
    "dashboard.today": "今日",
    "dashboard.this_week": "今週",
    "dashboard.this_month": "今月",
    "dashboard.bullish": "強気",
    "dashboard.neutral": "中立",
    "dashboard.bearish": "弱気",
    "dashboard.high": "高",
    "dashboard.medium": "中",
    "dashboard.low": "低",
    "dashboard.view_full_comparison": "完全な比較を表示",
    "dashboard.set_alert": "アラートを設定",
    "dashboard.market_share_label": "市場シェア",
    "dashboard.growth_rate": "成長率",
    "dashboard.features_tracked": "追跡中の機能",

    // Navbar
    "nav.dashboard": "ダッシュボード",
    "nav.competitors": "競合他社",
    "nav.insights": "洞察",
    "nav.news_digest": "ニュースダイジェスト",
    "nav.reports": "レポート",
    "nav.alerts": "アラート",
    "nav.settings": "設定",
    "nav.profile": "プロフィール",
    "nav.logout": "ログアウト",

    // Settings
    "settings.title": "設定",
    "settings.appearance": "外観",
    "settings.appearance_desc": "デバイスでのアプリの外観をカスタマイズ",
    "settings.theme": "テーマ",
    "settings.light": "ライト",
    "settings.dark": "ダーク",
    "settings.system": "システム",
    "settings.language_region": "言語と地域",
    "settings.language_region_desc": "希望する言語と地域設定を選択",
    "settings.display_language": "表示言語",
    "settings.choose_language": "希望する言語を選択",
    "settings.competitors": "競合他社",
    "settings.competitors_desc": "追跡中の競合他社を管理",
    "settings.competitor_list": "競合他社リスト",
    "settings.manage_competitors": "フォロー中の競合他社のリストを管理します。",
    "settings.manage": "管理",
    "settings.notifications": "通知",
    "settings.notifications_desc": "アラートと更新の受信方法を設定",
    "settings.slack": "Slack",
    "settings.slack_desc": "競合他社が変更を加えたときにワークスペースで通知を受け取ります。",
    "settings.email": "メール",
    "settings.email_desc": "競合他社のアクティビティに関するメールダイジェストを受信します。",
    "settings.data_privacy": "データとプライバシー",
    "settings.data_privacy_desc": "データとプライバシーの設定を管理",
    "settings.auto_refresh": "データの自動更新",
    "settings.auto_refresh_desc": "競合他社のデータをリアルタイムで自動更新",
    "settings.usage_analytics": "使用状況分析",
    "settings.usage_analytics_desc": "匿名の使用データを共有して製品の改善に協力",
    "settings.download_data": "マイデータをダウンロード",

    // Common
    "common.home": "ホーム",
    "common.invite_team": "チームを招待",
    "common.help_docs": "ヘルプとドキュメント",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.close": "閉じる",
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.success": "成功",

    // Days
    "days.mon": "月",
    "days.tue": "火",
    "days.wed": "水",
    "days.thu": "木",
    "days.fri": "金",
    "days.sat": "土",
    "days.sun": "日",
  },
  ar: {
    // Dashboard
    "dashboard.welcome": "مرحبًا بعودتك",
    "dashboard.subtitle": "إليك ما يحدث مع منافسيك اليوم.",
    "dashboard.competitors_tracked": "المنافسون المتتبعون",
    "dashboard.active_tracking": "التتبع النشط",
    "dashboard.total_features": "إجمالي الميزات المتتبعة",
    "dashboard.across_all": "عبر جميع المنافسين",
    "dashboard.market_mood": "مزاج السوق",
    "dashboard.avg_growth": "متوسط النمو",
    "dashboard.news_items": "عناصر الأخبار",
    "dashboard.recent_updates": "التحديثات الأخيرة",
    "dashboard.weekly_activity": "نظرة عامة على النشاط الأسبوعي",
    "dashboard.weekly_activity_desc": "اتجاهات النشاط لمنافسيك هذا الأسبوع",
    "dashboard.competitor_activity": "نشاط المنافسين",
    "dashboard.competitor_activity_desc": "تحديثات في الوقت الفعلي على منافسيك المتتبعين",
    "dashboard.no_competitors": "لم يتم اختيار منافسين بعد.",
    "dashboard.add_competitors": "إضافة منافسين",
    "dashboard.features": "ميزات",
    "dashboard.market_share": "حصة السوق",
    "dashboard.news_digest": "ملخص الأخبار",
    "dashboard.news_digest_desc": "أحدث إطلاقات المنتجات والتحديثات",
    "dashboard.all_news": "جميع الأخبار",
    "dashboard.key_insights": "الرؤى الرئيسية",
    "dashboard.you_are_first": "أنت الأول",
    "dashboard.first_to_market": "كن الأول في السوق بميزات مبتكرة.",
    "dashboard.view_opportunities": "عرض الفرص ←",
    "dashboard.competitor_planning": "المنافس يخطط لهذا",
    "dashboard.stay_informed": "ابق على اطلاع بإصدارات المنافسين القادمة.",
    "dashboard.see_predictions": "عرض التوقعات ←",
    "dashboard.competitor_lacks": "المنافس يفتقر إلى هذا",
    "dashboard.identify_gaps": "حدد الفجوات في عروض المنافسين واستفد منها.",
    "dashboard.explore_gaps": "استكشاف الفجوات ←",
    "dashboard.see_compare": "انظر كيف تقارن",
    "dashboard.quick_actions": "إجراءات سريعة",
    "dashboard.export_report": "تصدير التقرير",
    "dashboard.get_notified": "احصل على إشعار",
    "dashboard.compare_features": "مقارنة الميزات",
    "dashboard.upcoming_events": "الأحداث القادمة",
    "dashboard.today": "اليوم",
    "dashboard.this_week": "هذا الأسبوع",
    "dashboard.this_month": "هذا الشهر",
    "dashboard.bullish": "صعودي",
    "dashboard.neutral": "محايد",
    "dashboard.bearish": "هبوطي",
    "dashboard.high": "عالي",
    "dashboard.medium": "متوسط",
    "dashboard.low": "منخفض",
    "dashboard.view_full_comparison": "عرض المقارنة الكاملة",
    "dashboard.set_alert": "تعيين تنبيه",
    "dashboard.market_share_label": "حصة السوق",
    "dashboard.growth_rate": "معدل النمو",
    "dashboard.features_tracked": "الميزات المتتبعة",

    // Navbar
    "nav.dashboard": "لوحة التحكم",
    "nav.competitors": "المنافسون",
    "nav.insights": "الرؤى",
    "nav.news_digest": "ملخص الأخبار",
    "nav.reports": "التقارير",
    "nav.alerts": "التنبيهات",
    "nav.settings": "الإعدادات",
    "nav.profile": "الملف الشخصي",
    "nav.logout": "تسجيل الخروج",

    // Settings
    "settings.title": "الإعدادات",
    "settings.appearance": "المظهر",
    "settings.appearance_desc": "تخصيص كيفية ظهور التطبيق على جهازك",
    "settings.theme": "السمة",
    "settings.light": "فاتح",
    "settings.dark": "داكن",
    "settings.system": "النظام",
    "settings.language_region": "اللغة والمنطقة",
    "settings.language_region_desc": "حدد لغتك وإعداداتك الإقليمية المفضلة",
    "settings.display_language": "لغة العرض",
    "settings.choose_language": "اختر لغتك المفضلة",
    "settings.competitors": "المنافسون",
    "settings.competitors_desc": "إدارة منافسيك المتتبعين",
    "settings.competitor_list": "قائمة المنافسين",
    "settings.manage_competitors": "إدارة قائمة المنافسين المتابعين.",
    "settings.manage": "إدارة",
    "settings.notifications": "الإشعارات",
    "settings.notifications_desc": "تكوين كيفية تلقي التنبيهات والتحديثات",
    "settings.slack": "سلاك",
    "settings.slack_desc": "احصل على إشعار في مساحة العمل الخاصة بك عندما يجري المنافسون تغييرات.",
    "settings.email": "البريد الإلكتروني",
    "settings.email_desc": "تلقي ملخصات البريد الإلكتروني حول أنشطة المنافسين.",
    "settings.data_privacy": "البيانات والخصوصية",
    "settings.data_privacy_desc": "التحكم في تفضيلات البيانات والخصوصية الخاصة بك",
    "settings.auto_refresh": "تحديث البيانات تلقائيًا",
    "settings.auto_refresh_desc": "تحديث بيانات المنافسين تلقائيًا في الوقت الفعلي",
    "settings.usage_analytics": "تحليلات الاستخدام",
    "settings.usage_analytics_desc": "ساعد في تحسين المنتج من خلال مشاركة بيانات الاستخدام المجهولة",
    "settings.download_data": "تنزيل بياناتي",

    // Common
    "common.home": "الصفحة الرئيسية",
    "common.invite_team": "دعوة الفريق",
    "common.help_docs": "المساعدة والمستندات",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.close": "إغلاق",
    "common.loading": "جارٍ التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح",

    // Days
    "days.mon": "الإثنين",
    "days.tue": "الثلاثاء",
    "days.wed": "الأربعاء",
    "days.thu": "الخميس",
    "days.fri": "الجمعة",
    "days.sat": "السبت",
    "days.sun": "الأحد",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("app-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("app-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
